package com.digout.model.entity.user;

import com.digout.model.common.IssueType;
import com.digout.model.entity.common.AutoGeneratedIdentifier;
import com.digout.model.entity.user.UserOrderEntity;
import org.hibernate.annotations.Type;
import org.joda.time.DateTime;

import javax.persistence.*;

@Entity
@Table(name = "ORDER_ISSUES")
public class IssueEntity extends AutoGeneratedIdentifier {

    /**
     * 
     */
    private static final long serialVersionUID = 7894207036536468731L;

    @Column(name = "issue_type", nullable = false)
    @Enumerated(EnumType.STRING)
    private IssueType issueType;

    @Type(type = "org.joda.time.contrib.hibernate.PersistentDateTime")
    @Column(name = "report_date", nullable = false)
    private DateTime reportDate;

    @Column(name = "issue_details", nullable = true)
    private String issueDetails;

    @ManyToOne(targetEntity = UserOrderEntity.class, fetch = FetchType.LAZY)
    @JoinColumn(name = "order_id", nullable = false)
    private UserOrderEntity order;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private UserEntity user;

    public IssueEntity() {
    }

    public String getIssueDetails() {
        return this.issueDetails;
    }

    public IssueType getIssueType() {
        return this.issueType;
    }

    public UserOrderEntity getOrder() {
        return this.order;
    }

    public DateTime getReportDate() {
        return this.reportDate;
    }

    public UserEntity getUser() {
        return this.user;
    }

    public void setIssueDetails(final String issueDetails) {
        this.issueDetails = issueDetails;
    }

    public void setIssueType(final IssueType issueType) {
        this.issueType = issueType;
    }

    public void setOrder(final UserOrderEntity order) {
        this.order = order;
    }

    public void setReportDate(final DateTime reportDate) {
        this.reportDate = reportDate;
    }

    public void setUser(final UserEntity user) {
        this.user = user;
    }
}
