package com.digout.model.entity.user;

import com.digout.model.common.AddressAssignment;
import com.digout.model.entity.common.AutoGeneratedIdentifier;

import javax.persistence.*;

@Entity
@Table(name = "USER_ADDRESSES")
public class UserAddressEntity extends AutoGeneratedIdentifier {

    /**
     * 
     */
    private static final long serialVersionUID = -1239480155883866685L;
    @Column(name = "address_name", nullable = true)
    private String addressDefinition;
    @Column(name = "address_line", nullable = true)
    private String addressLine;
    @Column(name = "district", nullable = true)
    private String district;
    @Column(name = "postal_code", nullable = true)
    private String postalCode;
    @Column(name = "city", nullable = false)
    private String city;
    @Column(name = "region", nullable = true)
    private String region;

    @Column(name = "latitude", nullable = true)
    private String latitude;
    @Column(name = "longitude", nullable = true)
    private String longitude;
    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    @JoinColumn(name = "user_id", nullable = true)
    private UserEntity user;

    @Enumerated(value = EnumType.STRING)
    @Column(name = "assignment")
    private AddressAssignment assignment;

    @Transient
    private boolean changed;

    public UserAddressEntity() {
    }

    public String getAddressDefinition() {
        return this.addressDefinition;
    }

    public String getAddressLine() {
        return this.addressLine;
    }

    public AddressAssignment getAssignment() {
        return this.assignment;
    }

    public String getCity() {
        return this.city;
    }

    public String getDistrict() {
        return this.district;
    }

    public String getLatitude() {
        return this.latitude;
    }

    public String getLongitude() {
        return this.longitude;
    }

    public String getPostalCode() {
        return this.postalCode;
    }

    public String getRegion() {
        return this.region;
    }

    public UserEntity getUser() {
        return this.user;
    }

    public void setAddressDefinition(final String addressDefinition) {
        this.addressDefinition = addressDefinition;
    }

    public void setAddressLine(final String addressLine) {
        this.addressLine = addressLine;
    }

    public void setAssignment(final AddressAssignment assignment) {
        this.assignment = assignment;
    }

    public void setCity(final String city) {
        this.city = city;
    }

    public void setDistrict(final String district) {
        this.district = district;
    }

    public void setLatitude(final String latitude) {
        this.latitude = latitude;
    }

    public void setLongitude(final String longitude) {
        this.longitude = longitude;
    }

    public void setPostalCode(final String postalCode) {
        this.postalCode = postalCode;
    }

    public void setRegion(final String region) {
        this.region = region;
    }

    public void setUser(final UserEntity user) {
        this.user = user;
    }

    public boolean isChanged() {
        return changed;
    }

    public void setChanged(boolean changed) {
        this.changed = changed;
    }
}
