package com.digout.model.entity.user;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import org.hibernate.annotations.Type;
import org.joda.time.DateTime;

import com.digout.model.entity.common.AutoGeneratedIdentifier;
import com.digout.model.entity.product.ProductEntity;

@Entity
@Table(name = "USER_ORDERS")
public class UserOrderEntity extends AutoGeneratedIdentifier {
    private static final long serialVersionUID = -5191929153204615456L;

    @ManyToOne(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @JoinColumn(name = "buyer_id")
    private UserEntity buyer;

    @ManyToOne(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @JoinColumn(name = "seller_id")
    private UserEntity seller;

    @ManyToOne(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @JoinColumn(name = "product_id")
    private ProductEntity product;

    @ManyToOne(cascade = CascadeType.ALL)
    @JoinColumn(name = "address_id")
    private UserAddressEntity addressReceiver;

    @Type(type = "org.joda.time.contrib.hibernate.PersistentDateTime")
    @Column(name = "start_shipping_date", nullable = true)
    private DateTime startShippingDate;

    @Type(type = "org.joda.time.contrib.hibernate.PersistentDateTime")
    @Column(name = "order_date", nullable = true)
    private DateTime orderDate;

    @Type(type = "org.joda.time.contrib.hibernate.PersistentDateTime")
    @Column(name = "canceled_date", nullable = true)
    private DateTime canceledDate;

    @Column(name = "xml_response", nullable = true, length = 1500)
    private String xmlResponseFromBank;

    @Column(name = "is_paid", nullable = true)
    private Boolean paid;

    @Column(name = "bank_order_id", unique = true)
    private String uniqueOrderId;

    @Column(name = "carrier_code", nullable = true)
    private String carrierCode;

    @Column(name = "tracking_code", nullable = true)
    private String trackingCode;
    
    public UserOrderEntity() {
    }

    public UserAddressEntity getAddressReceiver() {
        return this.addressReceiver;
    }

    public UserEntity getBuyer() {
        return this.buyer;
    }

    public DateTime getCanceledDate() {
        return this.canceledDate;
    }

    public DateTime getOrderDate() {
        return this.orderDate;
    }

    public ProductEntity getProduct() {
        return this.product;
    }

    public UserEntity getSeller() {
        return this.seller;
    }

    public DateTime getStartShippingDate() {
        return this.startShippingDate;
    }

    public String getUniqueOrderId() {
        return this.uniqueOrderId;
    }

    public String getXmlResponseFromBank() {
        return this.xmlResponseFromBank;
    }

    public Boolean isPaid() {
        return this.paid;
    }

    public void setAddressReceiver(final UserAddressEntity addressReceiver) {
        this.addressReceiver = addressReceiver;
    }

    public void setBuyer(final UserEntity buyer) {
        this.buyer = buyer;
    }

    public void setCanceledDate(final DateTime canceledDate) {
        this.canceledDate = canceledDate;
    }

    public void setOrderDate(final DateTime orderDate) {
        this.orderDate = orderDate;
    }

    public void setPaid(final Boolean paid) {
        this.paid = paid;
    }

    public void setProduct(final ProductEntity product) {
        this.product = product;
    }

    public void setSeller(final UserEntity seller) {
        this.seller = seller;
    }

    public void setStartShippingDate(final DateTime startShippingDate) {
        this.startShippingDate = startShippingDate;
    }

    public void setUniqueOrderId(final String uniqueOrderId) {
        this.uniqueOrderId = uniqueOrderId;
    }

    public void setXmlResponseFromBank(final String xmlResponseFromBank) {
        this.xmlResponseFromBank = xmlResponseFromBank;
    }

    public String getCarrierCode() {
        return carrierCode;
    }

    public void setCarrierCode(String carrierCode) {
        this.carrierCode = carrierCode;
    }

    public String getTrackingCode() {
        return trackingCode;
    }

    public void setTrackingCode(String trackingCode) {
        this.trackingCode = trackingCode;
    }
}
