package com.digout.model.entity.user;

import com.digout.model.entity.common.AutoGeneratedIdentifier;

import javax.persistence.*;
import java.io.Serializable;

@Entity
@Table(name = "USER_FOLLOWER", uniqueConstraints = { @UniqueConstraint(columnNames = { "follower_id", "followed_id" }),
        @UniqueConstraint(columnNames = { "followed_id", "follower_id" }) })
public class UserFollowerEntity extends AutoGeneratedIdentifier implements Serializable {

    private static final long serialVersionUID = 6725215768861769658L;

    @ManyToOne(optional = false, cascade = CascadeType.ALL)
    @JoinColumn(name = "follower_id", nullable = false)
    private UserEntity follower;
    @ManyToOne(optional = false, cascade = CascadeType.ALL)
    @JoinColumn(name = "followed_id", nullable = false)
    private UserEntity followed;

    @Column(name = "is_following", nullable = false)
    private boolean following = false;

    @Transient
    private Boolean additionalFollowing;

    public Boolean getAdditionalFollowing() {
        return this.additionalFollowing;
    }

    public UserEntity getFollowed() {
        return this.followed;
    }

    public UserEntity getFollower() {
        return this.follower;
    }

    public boolean isFollowing() {
        return this.following;
    }

    public void setAdditionalFollowing(final Boolean additionalFollowing) {
        this.additionalFollowing = additionalFollowing;
    }

    public void setFollowed(final UserEntity followed) {
        this.followed = followed;
    }

    public void setFollower(final UserEntity follower) {
        this.follower = follower;
    }

    public void setFollowing(final boolean following) {
        this.following = following;
    }
}
