package com.digout.model.entity.user;

import com.digout.model.entity.common.AutoGeneratedIdentifier;

import javax.persistence.*;

@Entity
@Table(name = "USER_PHONES", uniqueConstraints = @UniqueConstraint(columnNames = { "id", "is_primary" }))
public class UserPhoneEntity extends AutoGeneratedIdentifier {
    /**
     * 
     */
    private static final long serialVersionUID = -6968127011200358462L;
    @Column(name = "phone_number", nullable = false)
    private String phoneNumber;
    @Column(name = "phone_name")
    private String phoneName;
    @Column(name = "is_primary", nullable = false)
    private boolean isPrimary;

    @ManyToOne(fetch = FetchType.LAZY, optional = false, cascade = CascadeType.ALL)
    @JoinColumn(name = "user_id", nullable = false)
    private UserEntity user;

    public UserPhoneEntity() {
    }

    public String getPhoneName() {
        return this.phoneName;
    }

    public String getPhoneNumber() {
        return this.phoneNumber;
    }

    public UserEntity getUser() {
        return this.user;
    }

    public boolean isPrimary() {
        return this.isPrimary;
    }

    public void setPhoneName(final String phoneName) {
        this.phoneName = phoneName;
    }

    public void setPhoneNumber(final String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public void setPrimary(final boolean primary) {
        this.isPrimary = primary;
    }

    public void setUser(final UserEntity user) {
        this.user = user;
    }
}
