package com.digout.model.entity.user;

import com.digout.model.entity.common.AutoGeneratedIdentifier;

import javax.persistence.*;

@Entity
@Table(name = "USER_COMMENTS")
public class UserCommentEntity extends AutoGeneratedIdentifier {
    private static final long serialVersionUID = -2921592425852373332L;

    @Column(name = "comment", nullable = false, length = 1024)
    private String comment;

    @ManyToOne(fetch = FetchType.LAZY, optional = false, cascade = CascadeType.ALL)
    @JoinColumn(name = "for_user_id", nullable = false)
    private UserEntity forUser;

    @ManyToOne(fetch = FetchType.LAZY, optional = false, cascade = CascadeType.ALL)
    @JoinColumn(name = "posted_by_id", nullable = false)
    private UserEntity postedBy;

    public String getComment() {
        return this.comment;
    }

    public UserEntity getForUser() {
        return this.forUser;
    }

    public UserEntity getPostedBy() {
        return this.postedBy;
    }

    public void setComment(final String comment) {
        this.comment = comment;
    }

    public void setForUser(final UserEntity forUser) {
        this.forUser = forUser;
    }

    public void setPostedBy(final UserEntity postedBy) {
        this.postedBy = postedBy;
    }
}
