package com.digout.model.entity.common;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

import org.hibernate.annotations.Type;
import org.joda.time.DateTime;

@Entity
@Table(name = "AUDIT_LOGS")
public class AuditLogEntity extends AutoGeneratedIdentifier {
    public static final class Builder {
        private String inputData;
        private String outputData;
        private String operationName;
        private String username;

        private Builder() {
        }

        public AuditLogEntity build() {
            AuditLogEntity log = new AuditLogEntity();
            log.setInputData(this.inputData);
            log.setOperationName(this.operationName);
            log.setOutputData(this.outputData);
            log.setUsername(this.username);

            return log;
        }

        public Builder withInput(final String input) {
            this.inputData = input;
            return this;
        }

        public Builder withOperation(final String opName) {
            this.operationName = opName;
            return this;
        }

        public Builder withOutput(final String output) {
            this.outputData = output;
            return this;
        }

        public Builder withUsername(final String userName) {
            this.username = userName;
            return this;
        }
    }

    private static final long serialVersionUID = -8672125677764723136L;
    public static Builder newBuilder() {
        return new Builder();
    }
    @Column(name = "input_data")
    private String inputData;
    @Column(name = "output_data")
    private String outputData;
    @Column(name = "operation_name")
    private String operationName;

    @Column(name = "username")
    private String username;

    @Column(name = "created_datetime", nullable = false)
    @Type(type = "org.joda.time.contrib.hibernate.PersistentDateTime")
    private DateTime created = DateTime.now();

    public DateTime getCreated() {
        return this.created;
    }

    public String getInputData() {
        return this.inputData;
    }

    public String getOperationName() {
        return this.operationName;
    }

    public String getOutputData() {
        return this.outputData;
    }

    public String getUsername() {
        return this.username;
    }

    public void setCreated(final DateTime created) {
        this.created = created;
    }

    public void setInputData(final String inputData) {
        this.inputData = inputData;
    }

    public void setOperationName(final String operationName) {
        this.operationName = operationName;
    }

    public void setOutputData(final String outputData) {
        this.outputData = outputData;
    }

    public void setUsername(final String username) {
        this.username = username;
    }
}
