package com.digout.model.entity.common;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

@Entity
@Table(name = "BANK_INFO")
public class BankInfoEntity extends AutoGeneratedIdentifier {

    /**
     * 
     */
    private static final long serialVersionUID = -6259224550159367981L;
    @Column(name = "name")
    private String name;
    @Column(name = "mode")
    private String mode;
    @Column(name = "version")
    private String version;
    @Column(name = "prov_user_ID")
    private String provUserId;
    @Column(name = "user_ID")
    private String userId;
    @Column(name = "merchant_ID")
    private String merchantId;
    @Column(name = "terminal_ID")
    private String terminalId;
    @Column(name = "transaction_type")
    private String transactionType;
    @Column(name = "installmentCnt")
    private String installmentCnt;
    @Column(name = "cardholder_present_code")
    private String cardHolderPresentCode;
    @Column(name = "moto_ind")
    private String motoInd;
    @Column(name = "original_retref_num")
    private String originalRetrefNum;
    @Column(name = "bank_uri")
    private String uri;
    @Column(name = "password")
    private String password;

    public BankInfoEntity() {
    }

    public String getCardHolderPresentCode() {
        return this.cardHolderPresentCode;
    }

    public String getInstallmentCnt() {
        return this.installmentCnt;
    }

    public String getMerchantId() {
        return this.merchantId;
    }

    public String getMode() {
        return this.mode;
    }

    public String getMotoInd() {
        return this.motoInd;
    }

    public String getName() {
        return this.name;
    }

    public String getOriginalRetrefNum() {
        return this.originalRetrefNum;
    }

    public String getPassword() {
        return this.password;
    }

    public String getProvUserId() {
        return this.provUserId;
    }

    public String getTerminalId() {
        return this.terminalId;
    }

    public String getTransactionType() {
        return this.transactionType;
    }

    public String getUri() {
        return this.uri;
    }

    public String getUserId() {
        return this.userId;
    }

    public String getVersion() {
        return this.version;
    }

    public void setCardHolderPresentCode(final String cardHolderPresentCode) {
        this.cardHolderPresentCode = cardHolderPresentCode;
    }

    public void setInstallmentCnt(final String installmentCnt) {
        this.installmentCnt = installmentCnt;
    }

    public void setMerchantId(final String merchantId) {
        this.merchantId = merchantId;
    }

    public void setMode(final String mode) {
        this.mode = mode;
    }

    public void setMotoInd(final String motoInd) {
        this.motoInd = motoInd;
    }

    public void setName(final String name) {
        this.name = name;
    }

    public void setOriginalRetrefNum(final String originalRetrefNum) {
        this.originalRetrefNum = originalRetrefNum;
    }

    public void setPassword(final String password) {
        this.password = password;
    }

    public void setProvUserId(final String provUserId) {
        this.provUserId = provUserId;
    }

    public void setTerminalId(final String terminalId) {
        this.terminalId = terminalId;
    }

    public void setTransactionType(final String transactionType) {
        this.transactionType = transactionType;
    }

    public void setUri(final String uri) {
        this.uri = uri;
    }

    public void setUserId(final String userId) {
        this.userId = userId;
    }

    public void setVersion(final String version) {
        this.version = version;
    }
}
