package com.digout.model.entity.common;

import com.digout.model.entity.product.ProductEntity;
import com.digout.model.entity.user.UserEntity;
import org.hibernate.annotations.Type;
import org.joda.time.DateTime;

import javax.persistence.*;

@Entity
@Table(name = "BANK_TRANSACTION_FAIL")
public class BankTransactionFailEntity extends AutoGeneratedIdentifier {

    /**
     * 
     */
    private static final long serialVersionUID = -8385851589386179042L;

    @Type(type = "org.joda.time.contrib.hibernate.PersistentDateTime")
    @Column(name = "transaction_date", nullable = false)
    private DateTime transactionDate;

    @ManyToOne
    @JoinColumn(name = "buyer_id", nullable = false)
    private UserEntity buyer;

    @Column(name = "error_message")
    private String errorMessage;

    @ManyToOne
    @JoinColumn(name = "product_id", nullable = false)
    private ProductEntity product;

    @Column(name = "request_xml", nullable = false, length = 1500)
    private String requestXml;

    @Column(name = "response_xml", nullable = false, length = 1500)
    private String responseXml;

    public BankTransactionFailEntity() {
    }

    public UserEntity getBuyer() {
        return this.buyer;
    }

    public String getErrorMessage() {
        return this.errorMessage;
    }

    public ProductEntity getProduct() {
        return this.product;
    }

    public String getRequestXml() {
        return this.requestXml;
    }

    public String getResponseXml() {
        return this.responseXml;
    }

    public DateTime getTransactionDate() {
        return this.transactionDate;
    }

    public void setBuyer(final UserEntity buyer) {
        this.buyer = buyer;
    }

    public void setErrorMessage(final String errorMessage) {
        this.errorMessage = errorMessage;
    }

    public void setProduct(final ProductEntity product) {
        this.product = product;
    }

    public void setRequestXml(final String requestXml) {
        this.requestXml = requestXml;
    }

    public void setResponseXml(final String responseXml) {
        this.responseXml = responseXml;
    }

    public void setTransactionDate(final DateTime transactionDate) {
        this.transactionDate = transactionDate;
    }
}
