package com.digout.model.entity.common;

import org.hibernate.annotations.Type;
import org.joda.time.DateTime;

import javax.persistence.*;

@Entity
@Table(name = "IMAGES")
@Inheritance(strategy = InheritanceType.JOINED)
public abstract class ImageEntity extends AutoGeneratedIdentifier implements ImageInfoAccessor {

    // @ManyToOne(targetEntity = StorageEntity.class, fetch = FetchType.LAZY)
    // @JoinColumn(name = "storage_id", nullable = false)
    // private StorageEntity storage;

    /**
     * 
     */
    private static final long serialVersionUID = 1389843243134067576L;

    @Column(name = "image_path", nullable = false)
    private String imagePath;

    @Column(name = "uploaded_datetime", nullable = false)
    @Type(type = "org.joda.time.contrib.hibernate.PersistentDateTime")
    private final DateTime uploaded = DateTime.now();

    @Column(name = "imgs_group", nullable = false)
    private String group;

    // public StorageEntity getStorage() {
    // return storage;
    // }
    //
    // public void setStorage(StorageEntity storage) {
    // this.storage = storage;
    // }

    @Override
    public String getGroup() {
        return this.group;
    }

    @Override
    public String getImagePath() {
        return this.imagePath;
    }

    @Override
    public void setGroup(final String group) {
        this.group = group;
    }

    @Override
    public void setImagePath(final String imagePath) {
        this.imagePath = imagePath;
    }

}
