package com.digout.model.entity.common;

import com.digout.model.common.StorageType;

import javax.persistence.*;

@Entity
@Table(name = "STORAGES")
public class StorageEntity extends AutoGeneratedIdentifier {

    /**
     * 
     */
    private static final long serialVersionUID = -5281627193319256055L;
    @Enumerated(EnumType.STRING)
    @Column(name = "type", nullable = false, unique = true)
    private StorageType storageType;
    @Column(name = "path", nullable = false)
    private String path;

    public String getPath() {
        return this.path;
    }

    public StorageType getStorageType() {
        return this.storageType;
    }

    public void setPath(final String path) {
        this.path = path;
    }

    public void setStorageType(final StorageType storageType) {
        this.storageType = storageType;
    }
}
