package com.digout.model.entity.product;

import javax.persistence.*;

import com.digout.model.entity.common.AutoGeneratedIdentifier;
import com.digout.model.entity.user.UserEntity;

@Entity
@Table(name = "FAVOURITE_PRODUCTS", uniqueConstraints = @UniqueConstraint(columnNames = { "product_id", "owner_id" }))
public class FavouriteProductEntity extends AutoGeneratedIdentifier {
    private static final long serialVersionUID = 7909125388487805899L;

    @ManyToOne(fetch = FetchType.LAZY, optional = false, cascade = CascadeType.ALL)
    @JoinColumn(name = "product_id", nullable = false)
    private ProductEntity product;
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "owner_id", nullable = false)
    private UserEntity owner;

    public UserEntity getOwner() {
        return this.owner;
    }

    public ProductEntity getProduct() {
        return this.product;
    }

    public void setOwner(final UserEntity owner) {
        this.owner = owner;
    }

    public void setProduct(final ProductEntity product) {
        this.product = product;
    }
}
