package com.digout.model.entity.product;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.digout.model.entity.common.AutoGeneratedIdentifier;
import com.digout.model.entity.user.UserEntity;
import org.hibernate.annotations.Type;
import org.joda.time.DateTime;

@Entity
@Table(name = "PRODUCT_COMMENTS")
public class ProductCommentEntity extends AutoGeneratedIdentifier {
    private static final long serialVersionUID = 5317105795951814671L;

    @Column(name = "comment", nullable = false, length = 1024)
    private String comment;

    @ManyToOne(targetEntity = ProductEntity.class, fetch = FetchType.LAZY)
    @JoinColumn(name = "product_id", nullable = false)
    private ProductEntity product;

    @ManyToOne(targetEntity = UserEntity.class, fetch = FetchType.LAZY)
    @JoinColumn(name = "posted_by_id", nullable = false)
    private UserEntity postedBy;

    @Type(type = "org.joda.time.contrib.hibernate.PersistentDateTime")
    @Column(name = "published_date", nullable = true)
    private DateTime publishedDate;

    public String getComment() {
        return this.comment;
    }

    public UserEntity getPostedBy() {
        return this.postedBy;
    }

    public ProductEntity getProduct() {
        return this.product;
    }

    public DateTime getPublishedDate() {
        return this.publishedDate;
    }

    public void setComment(final String comment) {
        this.comment = comment;
    }

    public void setPostedBy(final UserEntity postedBy) {
        this.postedBy = postedBy;
    }

    public void setProduct(final ProductEntity product) {
        this.product = product;
    }

    public void setPublishedDate(final DateTime publishedDate) {
        this.publishedDate = publishedDate;
    }
}
